//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMolde.Forms
{
    public partial class frmOperaciones_Nuevo
    {
        protected global::ProyectoMolde.Forms.frmOperaciones frmOperaciones;
    }
}
