//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneradorClases.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConecionServidores
    {
        public int id { get; set; }
        public string nombreConeccion { get; set; }
        public string servidor { get; set; }
        public string baseDatos { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
    }
}
