//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneradorClases.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSysDataBase
    {
        public string name { get; set; }
        public int database_id { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
