//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int id { get; set; }
        public string numeroOficina { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFinal { get; set; }
        public bool cargaResulExam { get; set; }
        public int idPacientes { get; set; }
        public int idDoctores { get; set; }
        public int idExamenes { get; set; }
        public int usuarioId { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        public virtual Examenes Examenes { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
