//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public Departamentos()
        {
            this.Municipios = new HashSet<Municipios>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int usuarioId { get; set; }
        public string codigoDane { get; set; }
    
        public virtual ICollection<Municipios> Municipios { get; set; }
    }
}
