//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctores
    {
        public Doctores()
        {
            this.Citas = new HashSet<Citas>();
        }
    
        public int id { get; set; }
        public string registroUnico { get; set; }
        public string especialidad { get; set; }
        public string direccionLaboral { get; set; }
        public long telefonoCorporacion { get; set; }
        public int idPersonas { get; set; }
        public int usuarioId { get; set; }
    
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
