//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examenes
    {
        public Examenes()
        {
            this.Citas = new HashSet<Citas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public int usuarioId { get; set; }
    
        public virtual ICollection<Citas> Citas { get; set; }
    }
}
