//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formularios
    {
        public Formularios()
        {
            this.OperacionesFormulario = new HashSet<OperacionesFormulario>();
        }
    
        public int id { get; set; }
        public string nombreFormulario { get; set; }
        public string urlFormulario { get; set; }
        public string nombreMostrar { get; set; }
        public int menuId { get; set; }
        public bool esVisible { get; set; }
        public int usuarioId { get; set; }
        public string estados { get; set; }
        public string iconOpcion { get; set; }
        public int indexVisibilidad { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual ICollection<OperacionesFormulario> OperacionesFormulario { get; set; }
    }
}
