//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public Menus()
        {
            this.Formularios = new HashSet<Formularios>();
        }
    
        public int id { get; set; }
        public string nombreMenu { get; set; }
        public Nullable<int> aplicacionWebId { get; set; }
        public int usuarioId { get; set; }
        public string estado { get; set; }
        public string icon { get; set; }
        public int indexVisibilidad { get; set; }
    
        public virtual ICollection<Formularios> Formularios { get; set; }
        public virtual AplicacionesWeb AplicacionesWeb { get; set; }
    }
}
