//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionesFormulario
    {
        public OperacionesFormulario()
        {
            this.PerfilesOperacionesFormulario = new HashSet<PerfilesOperacionesFormulario>();
            this.UsuariosOperacionesFormulario = new HashSet<UsuariosOperacionesFormulario>();
        }
    
        public int id { get; set; }
        public Nullable<int> formularioId { get; set; }
        public Nullable<int> operacionId { get; set; }
        public string descripcion { get; set; }
        public int usuarioId { get; set; }
    
        public virtual Formularios Formularios { get; set; }
        public virtual Operaciones Operaciones { get; set; }
        public virtual ICollection<PerfilesOperacionesFormulario> PerfilesOperacionesFormulario { get; set; }
        public virtual ICollection<UsuariosOperacionesFormulario> UsuariosOperacionesFormulario { get; set; }
    }
}
