//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public Pacientes()
        {
            this.Citas = new HashSet<Citas>();
        }
    
        public int id { get; set; }
        public Nullable<bool> polizaSeguros { get; set; }
        public Nullable<bool> particular { get; set; }
        public int idIps { get; set; }
        public int idPersonas { get; set; }
        public int usuarioId { get; set; }
    
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual ProveedorServicios ProveedorServicios { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
