//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles
    {
        public Perfiles()
        {
            this.PerfilesOperacionesFormulario = new HashSet<PerfilesOperacionesFormulario>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id { get; set; }
        public string nombrePerfil { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public int usuarioId { get; set; }
    
        public virtual ICollection<PerfilesOperacionesFormulario> PerfilesOperacionesFormulario { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
