//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public Personas()
        {
            this.Usuarios = new HashSet<Usuarios>();
            this.Doctores = new HashSet<Doctores>();
            this.Pacientes = new HashSet<Pacientes>();
        }
    
        public int id { get; set; }
        public string numeroDocumento { get; set; }
        public int documentoIdentidadId { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int municipioId { get; set; }
        public int grupoSanguineoId { get; set; }
        public int sexoId { get; set; }
        public System.DateTime fechaExpedicionCedula { get; set; }
        public int municipioExpedicionId { get; set; }
        public Nullable<int> barrioId { get; set; }
        public string direcccion { get; set; }
        public decimal estatura { get; set; }
        public decimal peso { get; set; }
        public string correo { get; set; }
        public int estadoCivilId { get; set; }
        public long telefonoFijo { get; set; }
        public long telefonoCelular { get; set; }
        public int usuarioId { get; set; }
        public Nullable<int> idExamen { get; set; }
        public Nullable<bool> foto { get; set; }
        public Nullable<bool> huella { get; set; }
        public string tipoDeZona { get; set; }
        public string ocupacion { get; set; }
        public Nullable<int> IdEps { get; set; }
    
        public virtual Barrios Barrios { get; set; }
        public virtual DocumentosIdentidad DocumentosIdentidad { get; set; }
        public virtual EstadosCivil EstadosCivil { get; set; }
        public virtual GruposSanguineo GruposSanguineo { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual Municipios Municipios1 { get; set; }
        public virtual Sexos Sexos { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
        public virtual ICollection<Doctores> Doctores { get; set; }
        public virtual ICollection<Pacientes> Pacientes { get; set; }
    }
}
