//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.UsuariosOperacionesFormulario = new HashSet<UsuariosOperacionesFormulario>();
        }
    
        public int id { get; set; }
        public string nombreUsuario { get; set; }
        public string clave { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string estado { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public int perfilId { get; set; }
    
        public virtual Perfiles Perfiles { get; set; }
        public virtual ICollection<UsuariosOperacionesFormulario> UsuariosOperacionesFormulario { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
